Homework 2
malatindez/dle_internship pull request #2
Opened 2022-05-12 17:49 UTC by malatindez

2022-05-22 14:00 UTC, Bonefest commented
Ещё, код в main.cc лучше как-то разделить на часть инициализации движка и часть инициализации твоего проекта. Можно это сделать разными способами: от простого разбиения на две отдельные функции, до более продвинутых, как в том же Hazel, где к main у юзера нет доступа и движок сам определяет когда юзеру пора инициализироваться.

2022-05-22 14:01 UTC, Bonefest requested changes

2022-05-24 11:01 UTC, malatindez commented on project/controller.cpp
> +        angles.x = float(saved_mouse_position_.x - input_.mouse_position().x) / 1000.0f * 2.0f * static_cast<float>(std::numbers::pi) / 180.0f;
++

2022-05-24 11:01 UTC, malatindez commented on project/controller.cpp
> +    if (input_.key_state('Q')) { angles.z -= 10.0f * delta_time * 2.0f * static_cast<float>(std::numbers::pi) / 180.0f; }
++

2022-05-24 11:01 UTC, malatindez commented on engine/components/spot-light.hpp
> +                    math::dot(light_data.normal, light_direction) *
++

2022-05-24 11:01 UTC, malatindez commented on engine/components/sphere.hpp
> +                return std::min(std::abs(-b - d), std::abs(-b + d)) / (2.0f * a);
++

2022-05-24 11:01 UTC, malatindez commented on engine/components/sphere.hpp
> +            float b = 2.0f * math::dot(oc, r.direction());
++

2022-05-24 11:01 UTC, malatindez commented on engine/components/point-light.hpp
> +                    math::dot(light_data.normal, light_direction) *
++

2022-05-24 11:01 UTC, malatindez commented on engine/components/light-data.hpp
> +        Color color;
++

2022-05-24 11:12 UTC, malatindez commented on engine/misc/camera-controller.cpp
> +    void CameraController::SetWorldAngles(math::vec3 const &angles)
++

2022-05-27 20:19 UTC, Bonefest requested changes

2022-05-27 20:19 UTC, Bonefest commented on engine/components/cube.hpp
> +            for (auto const &triangle : triangles_)
Для мешей мы будем переводить луч в локальное пространство меша. Благодаря этому, нам не нужно будет каждый раз пересчитывать позиции и нормали для вершин меша когда его трансформация поменялась.

После того как найдешь пересечение, найденную точку и нормаль нужно будет перевести обратно в мировые координаты.

Если пропустил, Эмиль об этом уже писал в render_interns_discussion3

2022-05-27 20:19 UTC, Bonefest commented on engine/components/point-light.hpp
> +            float specular = specular_intensity* static_cast<float>(std::pow(std::max(u, 0.0f), 32));
Используй постфикс f для функций pow, cos, sin и т.д

2022-05-27 20:19 UTC, Bonefest commented on project/controller.cpp
> +    camera_controller_.AddRelativeOffset(offset * delta_time);
Уместно было бы добавить какую-нибудь переменную для скорости движения (пусть она и будет равна 1)

2022-05-27 20:19 UTC, Bonefest commented on project/controller.cpp
> +    if (input_.key_state('Q')) { roll -= delta_time * engine::math::radians(180.0f); }
Магические числа, вынеси или в константу или в поле класса

2022-05-30 13:26 UTC, malatindez commented on engine/components/point-light.hpp
> +            float specular = specular_intensity* static_cast<float>(std::pow(std::max(u, 0.0f), 32));
++

2022-05-30 16:04 UTC, malatindez commented on project/controller.cpp
> +    if (input_.key_state('Q')) { roll -= delta_time * engine::math::radians(180.0f); }
++

2022-06-01 13:20 UTC, Bonefest reviewed
1. Не могу запустить код, т.к не находит obj file (при этом никаких проверок на это в коде я не вижу). Соответственно, не могу протестировать что ты сделал.
2. В задании № 2 не просят реализовывать свой парсер для obj файлов. Да и не попросят, уже есть достаточно библиотек. У нас ещё впереди будут задания, в которых мы будем работать с настоящими мешами, там это будет более уместно. Пока достаточно захардкодить куб - это нормально.
3. Придерживайся принципов KISS и YAGNI, не изобретай колесо.
4. Это ОК делать что-то дополнительно. Просто старайся делать это "что-то" после основного задания и только в случае, если осталось свободное время. 

Тебе ещё нужно реализовать отрисовку теней и захват объектов мышкой. В первую очередь сконцентрируйся на этом.

2022-06-03 09:55 UTC, Bonefest requested changes

2022-06-03 09:55 UTC, Bonefest commented on engine/components/directional-light.hpp
> +        float R = 5.0f; // if intersection was found then we multiply light color by 1
Не пиши такие комментарии. От них ноль толку, плюс это дубликат кода (причем неправильный): стоит тебе поменять код, так и комментарий нужно изменять. Лучше напиши что это вообще за поле или назови его как-нибудь более понятно. 

Более уместно было бы добавить небольшой комментарий где-то на 35-38 строку.

2022-06-03 09:55 UTC, Bonefest commented on engine/components/mesh.inl
> +    inline bool Mesh::CheckTriangleIntersection(std::vector<render::Vertex>::const_iterator &it,
Но у тебя ведь уже есть код для поиска пересечения луча и треугольника, применяй его.

2022-06-03 09:55 UTC, Bonefest commented on engine/misc/camera-controller.hpp
> +      math::vec4 t = (bl4 + (tl4 - bl4) * uv.v + (br4 - bl4) * uv.u);
имя t путает. Также, для генерации одного луча, нужно использовать матрицу напрямую: math::vec4(ndc.x, ndc.y, 1, 1) * camera_.inv_view_projection. То, что ты скопировал, оптимизация для случая, когда мы генерим луч для каждого пикселя (впринципе, для Raycast, если где-то дополнительно хранить bl, br, tl, можно тоже оптимизировать)

2022-06-03 09:55 UTC, Bonefest commented on project/controller.cpp
> +        t *= engine::math::radians(90.0f);
Магическая константа

2022-06-03 09:55 UTC, Bonefest commented on project/controller.hpp
> +        uv /= window_.window_size();
Обычно uv - это коорды в диапазоне [0, 1], координаты в диапазоне [-1, 1] лучше назвать ndc

2022-06-03 09:55 UTC, Bonefest commented on project/controller.hpp
> +    engine::ParallelExecutor executor{ std::max(1u, std::max(engine::ParallelExecutor::kMaxThreads - 4u, engine::ParallelExecutor::kHalfThreads)) };
Если у меня kMaxThreads < 4, будет оверфлоу

2022-06-04 00:35 UTC, malatindez commented on project/controller.cpp
> +const vec3 kBackwards{0, 0, -1};
++

2022-06-04 00:35 UTC, malatindez commented on engine/misc/camera-controller.hpp
> +    math::vec3 right_{1, 0, 0};
++

2022-06-04 00:35 UTC, malatindez commented on engine/misc/camera-controller.hpp
> +    [[nodiscard]] constexpr math::ivec2 const &size() const noexcept { return window_size_; }
++

2022-06-04 00:35 UTC, malatindez commented on engine/misc/camera-controller.cpp
> +            static_cast<float>(window_size_.x) / static_cast<float>(window_size_.y),
++

2022-06-04 00:36 UTC, malatindez commented on project/main.cc
> +    AddBasicSphere(registry, sphere);
++

2022-06-04 00:36 UTC, malatindez commented on engine/core/events/event.hpp
> +        [[nodiscard]] virtual uint8_t category_flags() const noexcept = 0;
++

2022-06-04 00:36 UTC, malatindez commented on project/controller.cpp
> +const float kMoveSpeed = 2.0f;
++

2022-06-04 00:36 UTC, malatindez commented on engine/misc/scene.cpp
> +              { planes.emplace_back(e, plane, transform, material); });
++

2022-06-04 00:36 UTC, malatindez commented on engine/misc/scene.cpp
> +    registry.group<Plane>(entt::get<Transform, Material>)
++

2022-06-04 00:36 UTC, malatindez commented on engine/components/triangle.hpp
> +        bool CheckIntersection(Transform const &, math::Intersection &i,
++

2022-06-04 00:37 UTC, malatindez commented on engine/components/point-light.hpp
> +            light_data.color += modifier * color * (ndotl * mat.albedo / distance);
++

2022-06-04 00:37 UTC, malatindez commented on engine/components/point-light.hpp
> +            if (!(nearest.exists() && transform.position != t.position) &&
++

2022-06-04 00:37 UTC, malatindez commented on engine/components/triangle.hpp
> +namespace engine::components
++

2022-06-04 00:37 UTC, malatindez commented on engine/components/transform.hpp
> +    math::vec3 position{0};
++

2022-06-04 00:37 UTC, malatindez commented on engine/components/cube.hpp
> +#include "entt/entt.hpp"
++

2022-06-04 00:38 UTC, malatindez commented on engine/pch.hpp
>  #include <Windows.h>
++

2022-06-04 00:38 UTC, malatindez commented on engine/components/directional-light.hpp
> +        float R = 5.0f; // if intersection was found then we multiply light color by 1
++

2022-06-04 00:38 UTC, malatindez commented on engine/misc/camera-controller.hpp
> +      math::vec4 t = (bl4 + (tl4 - bl4) * uv.v + (br4 - bl4) * uv.u);
++

2022-06-04 00:38 UTC, malatindez commented on project/controller.cpp
> +        t *= engine::math::radians(90.0f);
++

2022-06-04 00:39 UTC, malatindez commented on project/controller.hpp
> +        uv /= window_.window_size();
++

2022-06-04 00:39 UTC, malatindez commented on engine/components/mesh.inl
> +    inline bool Mesh::CheckTriangleIntersection(std::vector<render::Vertex>::const_iterator &it,
++

2022-06-04 00:39 UTC, malatindez commented on project/controller.hpp
> +    engine::ParallelExecutor executor{ std::max(1u, std::max(engine::ParallelExecutor::kMaxThreads - 4u, engine::ParallelExecutor::kHalfThreads)) };
++

2022-06-04 00:39 UTC, malatindez commented on engine/core/application.cpp
> +        tick.reset();
++

2022-06-04 00:39 UTC, malatindez commented on project/controller.cpp
> +            if (mbpe.mouse_button() == 1)
++

2022-06-04 00:40 UTC, malatindez commented on engine/components/point-light.hpp
> +            Transform const &transform, LightData &light_data, Material const &mat,
++

2022-06-04 00:40 UTC, malatindez commented on engine/components/point-light.hpp
> +            float modifier = ndotl * 0.25f * ndotl;
++

2022-06-04 00:40 UTC, malatindez commented on engine/components/cube.hpp
> +    class Cube
++

2022-06-04 19:44 UTC, malatindez commented on engine/misc/scene.cpp
> +                         { components::Sphere::CheckIntersection(transform, intersection, ray); });
++

2022-06-04 19:44 UTC, malatindez commented on engine/components/mesh-component.cpp
> +            rv |= CheckTriangleIntersection(it, i, local);
++

2022-06-04 20:28 UTC, malatindez commented on engine/misc/scene.cpp
> +            directional_lights.each([&ld, &mat, &find_intersection_if](const auto, auto &dirlight)
++

2022-06-05 21:56 UTC, Bonefest requested changes
В целом, посмотрел программу. Выглядит в общем норм, но соглашусь с замечаниями которые указывал Эмиль: сделай вообще всё статичным, т.к трудно определить всё ли правильно работает.

2022-06-05 21:56 UTC, Bonefest commented on engine/components/sphere.hpp
> +        static constexpr float Hit(core::math::Ray const &r, core::math::vec3 center,
Упустил ссылку

2022-06-05 21:56 UTC, Bonefest commented on engine/components/sphere.hpp
>      struct Sphere
И кстати, в целом, у тебя получается немного не так, как Эмиль просил. Было бы правильней, если бы у тебя код для поиска пересечения был вообще где-то отдельно, в мат. библиотеке. Например maths::Sphere, maths::Plane, ...

А вот уже в этом файле ты бы наследовался от того объекта и добавлял свою высокоуровневую логику. Так как это ecs, можно было бы даже не создавать ещё один компонент, а просто в самой системе добавить функции, которые бы делали свои высокоуровневые операции (например перевод в локально пространство объекта).

У тебя сейчас нет такого разделения и сфера содержит почему-то материал. Представь, что у нас новое задание, в котором нам нужно будет рассчитать ограничивающую сферу для меша. С твоим подходом у нас эта сфера ещё почему-то будет хранить материал.

2022-06-06 02:42 UTC, malatindez commented on engine/components/sphere.hpp
> +        static constexpr float Hit(core::math::Ray const &r, core::math::vec3 center,
++

2022-06-06 02:42 UTC, malatindez commented on engine/components/sphere.hpp
>      struct Sphere
++

2022-06-07 17:09 UTC, malatindez commented on project/controller.cpp
> +        vec3 obj_offset = a.PointAtParameter(selected_object_distance_ * dot(a.direction(), b.direction()));
++

2022-06-07 17:09 UTC, malatindez commented on engine/components/sphere-renderer.hpp
> +    struct SphereRenderer
++

2022-06-07 17:14 UTC, merged