Homework 4
malatindez/dle_internship pull request #4
Opened 2022-07-18 06:35 UTC by malatindez

2022-07-19 19:26 UTC, Bonefest requested changes

2022-07-19 19:26 UTC, Bonefest commented on d3d/controller.hpp
> +    std::vector<std::function<void(float)>> &update_callbacks() { return update_callbacks_; }
Хорошая практика для коллбеков создавать алиасы, например UpdateCb

2022-07-19 19:26 UTC, Bonefest commented on d3d/main.cc
> +    auto controller = std::make_shared<Controller>(*static_cast<Window *>(window.get()));
Опасный дизайн, т.к может быть dangling reference

2022-07-19 19:26 UTC, Bonefest commented on d3d/renderer.cpp
> +        depth_stencil_desc.DepthFunc = D3D11_COMPARISON_LESS;
В этом задании depth test точно лишний, но если даже его и включаешь - переходи сразу на reversed z, т.е очищай в 0 текстуру глубины, а здесь используй GREATER_EQUAL

2022-07-19 19:26 UTC, Bonefest commented on engine/direct3d/shader.cpp
> +            uniform_buffer_ = direct3d::Buffer(InitializeUniformBuffer(uniform_buffer_size + 0xf & 0xfffffff0));
Я бы это округление вынес в какую-нибудь отдельную функцию, чтобы с самого её названия было понятно что ты делаешь

2022-07-19 19:26 UTC, Bonefest commented on engine/direct3d/shader.cpp
> +            ss << core::debug_utils::CurrentSourceLocation() << "[" << pixel_path << "] Pixel shader compilation error: " << std::string_view(err_str);
У тебя такая конструкция повторяется пару раз, вынеси её в одну функцию что-то в духе BuildString(location,  "[", ...);

2022-07-19 19:26 UTC, Bonefest commented on engine/direct3d/shader.hpp
> +        direct3d::Buffer uniform_buffer_;
В целом, этот класс не очень подходящее место для uniform buffer, да и не в каждой программе он нужен. Лучше создай его в отдельном месте

2022-07-20 17:57 UTC, malatindez commented on d3d/controller.hpp
> +    std::vector<std::function<void(float)>> &update_callbacks() { return update_callbacks_; }
++

2022-07-20 17:57 UTC, malatindez commented on d3d/main.cc
> +    auto controller = std::make_shared<Controller>(*static_cast<Window *>(window.get()));
++

2022-07-20 18:39 UTC, malatindez commented on engine/direct3d/shader.cpp
> +            uniform_buffer_ = direct3d::Buffer(InitializeUniformBuffer(uniform_buffer_size + 0xf & 0xfffffff0));
++

2022-07-20 20:20 UTC, Bonefest commented on engine/direct3d/shader.hpp
> +        direct3d::Buffer uniform_buffer_;
А могут и не быть, а может быть два юниформ буфера, а может быть structured buffer, а может быть нужен RWBuffer (например, комбинация per-model uniform buffer + RWBuffer). Это чисто угадывание того что пользователю нужно. Конкретно в данном задании это может быть не проблемой, но в будущем это может стать плохим дизайном, когда создается буфер, который мне по факту и не нужен. А если и нужен, то обычно все равно создается какая-нибудь абстракция, например Sky, которая все равно является более удачным место для таких вещей. Шейдера - это просто часть PSO и не больше того, их можно перезагружать, кешировать, но добавлять к ним какую-нибудь логику - это запутать пользователя.

2022-07-20 20:26 UTC, malatindez commented on d3d/renderer.cpp
> +        depth_stencil_desc.DepthFunc = D3D11_COMPARISON_LESS;
++

2022-07-20 20:53 UTC, malatindez commented on engine/direct3d/shader.cpp
> +            ss << core::debug_utils::CurrentSourceLocation() << "[" << pixel_path << "] Pixel shader compilation error: " << std::string_view(err_str);
Не уверен, стоит ли это делать. 
Повторяется лишь в двух местах, не стал выносить т.к. это выглядит более понятным чем `BuildString(core::debug_utils::CurrentSourceLocation(), pixel_path, "Pixel shader compilation error: ", std::string_view(err_str))`
И вдруг понадобиться больше элементов выводить
Планировал `std::format` использовать, но он `experimental` в MSVC и лишь в `c++latest` доступен.

2022-07-20 20:53 UTC, malatindez commented on engine/direct3d/shader.hpp
> +        direct3d::Buffer uniform_buffer_;
Решил вынести в Triangle юниформу

2022-07-20 21:19 UTC, Bonefest commented on engine/direct3d/shader.cpp
> +            ss << core::debug_utils::CurrentSourceLocation() << "[" << pixel_path << "] Pixel shader compilation error: " << std::string_view(err_str);
Да, тогда точно не стоит. Мне почему-то показалось что таких мест больше. На самом деле, мне что первый, что второй варианты не очень нравятся. std::format было бы самое то, но лучше не надо)

2022-07-20 21:27 UTC, Bonefest commented on engine/direct3d/shader.hpp
> +        direct3d::Buffer uniform_buffer_;
Имхо, но это гораздо логичней. Мне удобней мыслить в терминах графических пассов, например depth prepass, shadow pass, light injection pass или вот как у тебя, sky pass или triangle pass. И вот на эти пассы юниформ буферы как-то более логично ложатся. Вулкан и дх12, кстати, вообще вводят эти термины и используют их в своём API, правда там это не так размыто, как у меня, и имеет дополнительные преимущества.

2022-07-21 15:37 UTC, Bonefest commented on engine/direct3d/shader.hpp
> +        direct3d::Buffer uniform_buffer_;
Ну вообще, мысль о том, что у нас есть per-program-specific юниформы почти всегда правильная. Я просто не уверен, что этот буфер должен создаваться именно в ShaderProgram. Здесь должно быть что-то ещё, что содержит эти шейдера и связанные с ними данные. Хотя и такой вариант +- имеет место быть и немного напоминает что-то похожее с learnopengl, но там правда ситуация чуть другая. Вот то, что ты говоришь про "per thread" вот мне очень это напоминает. И если бы оно было именно так реализовано тогда да, это было бы очень круто, для мини-движка это очень удобно, да ещё и код был бы очень красивый.

2022-07-25 18:23 UTC, merged