Homework 5
malatindez/dle_internship pull request #5
Opened 2022-08-09 11:46 UTC by malatindez

2022-08-29 20:49 UTC, Bonefest requested changes
Не делай в задании всё сразу. Вещи, которые нам точно не нужны, старайся не объявлять. Это просто усложняет проверку задания, т.к нужно тратить время на поиск кода именно самого задания.

Движок переусложнён, как по мне, но само приложение мне понравилось: выглядит красиво и работает правильно.

2022-08-29 20:49 UTC, Bonefest commented on engine/subsystems/render/skybox-manager.cpp
> +        direct3d::api::devcon->DrawIndexed(cube_ib_->size(), 0, 0);
Нам достаточно нарисовать треугольник. Эмиль, кажется, об способе в лекции рассказывал

2022-08-29 20:49 UTC, Bonefest commented on engine/subsystems/render/skybox-manager.cpp
> +        const std::array<core::math::vec3, 8> kSkyboxVertices =
Это также лишнее. Но можешь вынести его в отдельный файл. В 7 задании нам нужно создать дефолтные модели, возможно, эту информацию можно использовать

2022-08-29 20:49 UTC, Bonefest commented on engine/subsystems/render/skybox-manager.cpp
> +         {"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0}
У нас не будет ничего вообще на входе

2022-08-29 20:49 UTC, Bonefest commented on runtime_directory/assets/shaders/skybox/vs.hlsl
> +	row_major matrix camera_model;
Добавь префикс g_

2022-08-29 20:49 UTC, Bonefest commented on runtime_directory/assets/shaders/skybox/vs.hlsl
> +    vout.PosH = mul(mul(float4(vin.PosL, 1.0f), camera_model), view_projection).xyww;
Вместо этого кода, генерируй координаты треугольника с помощью SV_VertexID и, используя, frustum corners, генерируй направление.

2022-08-29 20:49 UTC, Bonefest commented on runtime_directory/assets/shaders/test-cube/ps.hlsl
> +float4 ps_main(float4 pos : SV_POSITION, float2 texcoord : TEXCOORD) : SV_TARGET
По условию задания, объедини ps + vs шейдера в один файл

2022-08-29 20:49 UTC, Bonefest commented on d3d_test/controller.cpp
> +    registry.get<TransformComponent>(cube).position = vec3{ 0,5,0 };
Вообще, project-specific код меня мало интересует, но почему ты не сделаешь .get() один раз и потом переиспользуешь ссылку?

2022-08-29 20:49 UTC, Bonefest commented on engine/subsystems/render/skybox-manager.cpp
> +        registry.emplace<components::TagComponent>(rv, components::TagComponent{ .tag = "Skybox" });
Здесь бы и entt::tag подошел

2022-08-29 20:49 UTC, Bonefest commented on d3d_test/renderer.cpp
> +    render::ModelSystem::instance()->Render();
Сначала рисуются меши, а потом только небо (с максимальной глубиной). Таким образом мы не нарисуем небо там, где оно чем-нибудь будет перекрываться.

2022-08-29 22:21 UTC, malatindez commented on d3d_test/controller.cpp
> +    registry.get<TransformComponent>(cube).position = vec3{ 0,5,0 };
Разницы в данном конкретном случае почти нет, быстро скопировал и отредактировал нужные данные, но тут ты прав.

2022-08-30 11:01 UTC, malatindez commented on engine/subsystems/render/skybox-manager.cpp
> +        direct3d::api::devcon->DrawIndexed(cube_ib_->size(), 0, 0);
++

2022-08-30 11:02 UTC, malatindez commented on engine/subsystems/render/skybox-manager.cpp
> +        const std::array<core::math::vec3, 8> kSkyboxVertices =
++

2022-08-30 11:02 UTC, malatindez commented on engine/subsystems/render/skybox-manager.cpp
> +         {"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0}
++

2022-08-30 11:02 UTC, malatindez commented on runtime_directory/assets/shaders/skybox/vs.hlsl
> +	row_major matrix camera_model;
++

2022-08-30 11:03 UTC, malatindez commented on runtime_directory/assets/shaders/skybox/vs.hlsl
> +    vout.PosH = mul(mul(float4(vin.PosL, 1.0f), camera_model), view_projection).xyww;
++

2022-08-30 11:03 UTC, malatindez commented on runtime_directory/assets/shaders/test-cube/ps.hlsl
> +float4 ps_main(float4 pos : SV_POSITION, float2 texcoord : TEXCOORD) : SV_TARGET
++

2022-08-30 11:04 UTC, malatindez commented on d3d_test/controller.cpp
> +    registry.get<TransformComponent>(cube).position = vec3{ 0,5,0 };
++

2022-08-30 11:05 UTC, malatindez commented on d3d_test/renderer.cpp
> +    render::ModelSystem::instance()->Render();
++

2022-08-31 11:11 UTC, DmitrySarafaniuk commented on engine/subsystems/render/skybox-manager.cpp
> +        direct3d::api::devcon4->OMSetDepthStencilState(direct3d::states::geq_depth, 0);
Во время отрисовки неба в depth ничего писать не нужно. Сейчас используется geq_depth, который указан как ReadOnlyDepthStencilState, но при этом записывает depth.

2022-08-31 11:13 UTC, DmitrySarafaniuk commented
.hlsli файлы оборачивай, пожалуйста, в #ifndef X #define X #endif.

2022-08-31 11:14 UTC, DmitrySarafaniuk commented on engine/core/engine.cpp
> +        direct3d::api::Deinit();
Деиницилизация должна быть в обратном порядке инициализации.

2022-08-31 11:15 UTC, DmitrySarafaniuk commented on runtime_directory/assets/shaders/test-cube/test-cube.hlsl
> +VS_OUT vs_main(VS_INPUT input)
Opaque.hlsl рисует opaque об'екты, но при этом есть Test-cube.hlsl, который по факту делает то же самое. Либо этот Test-cube.hlsl нужно переименовать во что-то по типу PrimitiveObjects.hlsl (потому что не будем же мы создавать отдельный шейдер Test-sphere.hlsl, Test-capsule.hlsl и т.д.) или сделать так, чтобы куб мог рисоваться через Opaque.hlsl. 
Лучше второй вариант, потому что когда пойдут Emissive.hlsl и т.п., то в первом случае придётся адаптировать каждый отдельный шейдер.

2022-08-31 11:24 UTC, DmitrySarafaniuk commented on engine/subsystems/render/detail/opaque-render-system.cpp
> +        for (const auto &instance : instances_)
Не совсем понятно, где находится сортировка по материалам. Вижу, что инстанцирование работает, но OpaqueRenderSystem проходится по инстансам, не беря во внимание материал (в OnInstancesUpdated по материалам проходимся, но просто помещаем их в InstanceInfo). Если поменять текстуру меша одного из рыцарей (например, для шлема) или поставить 3 куба (2 с одной текстурой, а 3й - с другой), будет ли правильно работать инстанцирование?
Сделай, пожалуйста, какой-то меш с другим материалом, чтобы сразу было видно, что всё ок.

2022-08-31 13:34 UTC, malatindez commented on runtime_directory/assets/shaders/test-cube/test-cube.hlsl
> +VS_OUT vs_main(VS_INPUT input)
test-cube сделан лишь для пятого задания, чтобы менять семплеры.
Или нам будет нужно менять семплеры для объектов в opaque?

2022-08-31 13:59 UTC, DmitrySarafaniuk commented on runtime_directory/assets/shaders/test-cube/test-cube.hlsl
> +VS_OUT vs_main(VS_INPUT input)
Семплеры не важно где менять, главное чтобы был виден эффект от изменений. Если бы куб рисовался в Opaque шейдере с остальными мешами, то мы всё равно видели бы разницу.

2022-08-31 22:43 UTC, malatindez commented on engine/subsystems/render/skybox-manager.cpp
> +        direct3d::api::devcon4->OMSetDepthStencilState(direct3d::states::geq_depth, 0);
Исправлено

2022-08-31 22:43 UTC, malatindez commented on engine/core/engine.cpp
> +        direct3d::api::Deinit();
Исправлено

2022-08-31 22:50 UTC, malatindez commented on runtime_directory/assets/shaders/test-cube/test-cube.hlsl
> +VS_OUT vs_main(VS_INPUT input)
Исправлено

2022-08-31 22:51 UTC, malatindez commented on engine/subsystems/render/detail/opaque-render-system.cpp
> +        for (const auto &instance : instances_)
Да, там была проблема с материалами, переделал систему инстансов и исправил

2022-09-05 10:03 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque.hlsl
> +	output.pos = mul(input.pos, world_transform);
Я рассчитываю результат умножения world на mesh to model еще на этапе создания Instance. Нет ведь смысла это делать в шейдере, раз для каждой вершины одно и то же значение.

2022-09-05 10:03 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque.hlsl
> +	output.pos = mul(input.pos, world_transform);
А конкретнее -- opaque_render_system.cpp, line 173

2022-09-05 10:06 UTC, malatindez commented on runtime_directory/assets/shaders/skybox/skybox.hlsl
> +  float4 ray = bl4 + right4 * vertex_coords.x * 2 + up4 * vertex_coords.y * 2;
Сделал я так, ибо мне показалось, что вычисление луча лишь для трёх вершин на видеокарте займёт меньше времени, чем 1 вычисление на процессоре плюс перекидывание через шину на видеокарту.

2022-09-05 10:07 UTC, malatindez commented on runtime_directory/assets/shaders/skybox/skybox.hlsl
> +  float4 PosH : SV_POSITION;
Раньше обозначали half-vector и Location(в прошлой версии шейдера), а сейчас не несут такого же смысла. Исправлю.

2022-09-05 10:10 UTC, malatindez commented on engine/direct3d11/states.cpp
> +    ReadOnlyRasterizerState cull_none;
Инициализация `states` возможна лишь через `friend class api`, да и он сам их инициализирует. Но по поводу deinit ты прав, да. Может стоило бы перенести в singleton `states`, а `Init` и `Deinit` сделать доступными лишь `api`, где находится сама инициализация D3D

2022-09-05 10:26 UTC, malatindez commented on d3d_test/controller.cpp
> +            registry.emplace<ModelInstanceComponent>(cube).kInstanceId = model_instance.kInstanceId;
Исправил. Данный префикс обозначает что значение является const, в данном случае не несёт смысла.

2022-09-05 10:30 UTC, malatindez commented on d3d_test/controller.cpp
> +            model_instance.model_id = cube_copy_id;
Из-за идеи с рендером одного меша с несколькими материалами, нужно ведь это как-то протестировать. А ModelLoader из FBX этого не позволит. Поэтому я загрузил куб и создал новый инстанс на основе его модели и меша с использованием нового материала.

2022-09-05 10:35 UTC, malatindez commented on d3d_test/controller.cpp
> +            registry.emplace<OpaqueComponent>(cube);
Логично, поправлю. Моя идея разделения была в том, что OpaqueComponent - пустой тег, который обозначает метод рендеринга, а ModelInstanceComponent является ссылкой на сам объект, который нужно отрисовать.

2022-09-05 10:37 UTC, malatindez commented on d3d_test/renderer.cpp
> +    DrawTestCube();
Лишь для теста, чтобы показать, что можно отрисовывать через DrawIndexedInstanced меши с разными материалами.

2022-09-05 10:37 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque.hlsl
> +SamplerState SampleType;
Исправлено

2022-09-05 11:48 UTC, malatindez commented on engine/direct3d11/states.cpp
> +    ReadOnlyRasterizerState cull_none;
Чтобы можно было писать direct3d::states, а не direct3d::api::states. 
Код будет выглядеть чуток чище

2022-09-06 19:43 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque.hlsl
> +	output.pos = mul(input.pos, world_transform);
Исправлено

2022-09-06 19:43 UTC, malatindez commented on engine/direct3d11/states.cpp
> +    ReadOnlyRasterizerState cull_none;
Исправлено

2022-09-06 19:43 UTC, malatindez commented on d3d_test/controller.cpp
> +            model_instance.mesh_instances.push_back(render::MeshInstance{ .mesh_id = 0, .material_id = 1 });
Исправлено

2022-09-06 19:43 UTC, malatindez commented on engine/render/model.hpp
> +        std::vector<Material> materials;
Исправлено

2022-09-06 19:44 UTC, malatindez commented on d3d_test/controller.cpp
> +            model_instance.model_id = cube_copy_id;
Исправлено

2022-09-06 19:44 UTC, malatindez commented on d3d_test/controller.cpp
> +    render::ModelSystem::instance()->OnInstancesUpdated(registry);
Исправлено

2022-09-08 11:42 UTC, malatindez commented on runtime_directory/assets/shaders/skybox/skybox.hlsl
> +  vout.ray_direction = ray.xyz / ray.w;
Исправлено

2022-09-08 11:42 UTC, malatindez commented on runtime_directory/assets/shaders/skybox/skybox.hlsl
> +  vout.sv_position = float4(vertex_coords * 4 - float2(1, 1), 0, 1);
Исправлено

2022-09-08 11:42 UTC, malatindez commented on runtime_directory/assets/shaders/skybox/skybox.hlsl
> +  float4 ray = g_bl + g_right * vertex_coords.x * 2 + g_up * vertex_coords.y * 2;
Исправлено

2022-09-08 11:42 UTC, malatindez commented on runtime_directory/assets/shaders/skybox/skybox.hlsl
>    if (vin.vertex == 0) { vertex_coords = float2(0, 1); }
Исправлено

2022-09-08 11:42 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque.hlsl
>  #include "../globals/vs.hlsli"
Исправлено

2022-09-08 11:42 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque.hlsl
> +cbuffer PerFrame : register(b1)
Исправлено

2022-09-08 12:04 UTC, malatindez commented on runtime_directory/assets/shaders/skybox/skybox.hlsl
> +  float4 g_up;
Исправлено

2022-09-08 12:06 UTC, malatindez commented on d3d_test/controller.cpp
> +        render::ModelSystem::instance().AddOpaqueInstance(model_id, registry, knight);
Это необходимо в случае, если у нас будут разные сцены -- таким образом проще с ними оперировать, да и если передавать параметром -- проще с кодом работать

2022-09-08 12:06 UTC, malatindez commented on engine/subsystems/render/detail/opaque-render-system.cpp
> +        std::vector<entt::entity> instances;
Исправил

2022-09-08 12:16 UTC, malatindez commented on engine/subsystems/render/detail/opaque-render-system.hpp
> +        std::unordered_map<uint64_t, ModelInstance> model_instances_;
Исправлено

2022-09-08 12:16 UTC, malatindez commented on engine/subsystems/render/detail/opaque-render-system.hpp
>          direct3d::DynamicUniformBuffer<core::math::mat4> mesh_to_model_buffer_;
Исправлено

2022-09-08 12:16 UTC, malatindez commented on engine/subsystems/render/detail/opaque-render-system.hpp
> +        std::set<entt::entity> instances;
Исправлено

2022-09-30 12:59 UTC, e-kabirov approved these changes
Finally approved 🙂

2022-09-30 17:32 UTC, merged