Homework 7
malatindez/dle_internship pull request #6
Opened 2022-09-30 18:07 UTC by malatindez

2022-10-03 21:04 UTC, Bonefest requested changes

2022-10-03 21:04 UTC, Bonefest commented on runtime_directory/assets/shaders/post-processing/hdr-to-ldr-ps.hlsl
> +  const float gamma = 1.0f / 2.2f;
Такие значения желательно тоже выносить где-то хотя бы в общее место. В реальном мире оно может изменяться пользователем.

2022-10-03 21:04 UTC, Bonefest commented on runtime_directory/assets/shaders/post-processing/hdr-to-ldr-ps.hlsl
> +  ldr = AdjustGamma(ldr, gamma);
AdjustGamma - неверное название. Тут больше ApplyGammaCorrection или что-то в этом духе

2022-10-09 10:19 UTC, e-kabirov commented
- Skybox не PBR
- IBL не добавлено

2022-10-09 11:43 UTC, e-kabirov commented on runtime_directory/assets/shaders/opaque/ps-helpers.hlsli
> +  if (RoS < 0.0)
Везде нужно клампить dot product в расчёте освещения не с нулём, а с 0.0001 типо. У тебя потом будет dot product дальше иначе равен почти нулю или нулю и будет деление на нуль или сверхмалое число

2022-10-09 11:45 UTC, e-kabirov commented on runtime_directory/assets/shaders/opaque/ps-helpers.hlsli
> +    float attenuation = (1.0f - cosa); // solid_angle / 2.0f * float(std::numbers::pi)
Здесь я делал ошибку, нужно всё же не attenuation считать, а именно solidAngle Для корректного решения интеграла по полусфере, поэтому на 2PI домножай

2022-10-09 11:47 UTC, e-kabirov commented on runtime_directory/assets/shaders/opaque/ps-helpers.hlsli
> +    return F * G * saturate(D * attenuation / (4 * ndotv));
saturate тут не нужен, просто max, зачем лишняя min операция?

2022-10-09 11:51 UTC, e-kabirov commented on runtime_directory/assets/shaders/post-processing/hdr-to-ldr-ps.hlsl
> +  const float gamma = 1.0f / 2.2f;
Я потом написал, что эта операция не нужна, у тебя итак Albedo DDS текстуры входные в sRGB формате.
А вот текстуры PBR для кубиков надо в корректном формате пересохранить в DDS, через Paint.Net даже

2022-10-09 11:56 UTC, e-kabirov commented on runtime_directory/assets/shaders/emissive/emissive-ps.hlsl
> +	float3 fragment_position : FRAGMENT_POSITION;
это worldPos, самое дефолтное название, или posWS

2022-10-09 11:58 UTC, e-kabirov commented on runtime_directory/assets/shaders/emissive/emissive-ps.hlsl
> +	bool use_emissive_texture : USE_EMISSIVE_TEXTURE;
Это вообще зачем нужно, если это униформа?

2022-10-09 12:01 UTC, e-kabirov commented on runtime_directory/assets/shaders/emissive/emissive-vs.hlsl
> +	int use_emissive_texture;
ВСЕ униформы с g_ префиксами

2022-10-09 12:02 UTC, e-kabirov commented on runtime_directory/assets/shaders/emissive/emissive-vs.hlsl
> +	output.power = power;
Это должно быть Per Instance данными

2022-10-09 12:03 UTC, e-kabirov commented on engine/subsystems/render/detail/emissive-render-system.cpp
> +                        buffer.emissive_color = material.emissive_color;
Ты должен был сделать это по заданию PerInstance данными, а не частью материала

2022-10-09 12:06 UTC, e-kabirov commented on d3d_test/controller.cpp
> +        render::ModelSystem::instance().AddEmissiveInstance(model_id, registry, entity, { render::EmissiveMaterial(vec3{0.988, 0.933, 0.655}, 5) });
Я говорил, что emissive для сфер света и значение radiance источника света должны быть одинаковыми для консистентности картинки, поскольку логически это одинаковые значения, но при этом хранятся они раздельно, так как источник света со светящейся сферой в движке не должны быть связанными

2022-10-09 12:09 UTC, e-kabirov commented on runtime_directory/assets/shaders/opaque/ps-helpers.hlsli
> +  float3 color;
Почему color и power раздельны? Почему color не используется? В шейдер они уже перемноженными должны придти

2022-10-09 12:10 UTC, e-kabirov commented on engine/subsystems/render/detail/emissive-render-system.cpp
> +                        buffer.emissive_color = material.emissive_color;
И почему на power не умножается?

2022-10-12 05:38 UTC, malatindez commented on engine/subsystems/render/detail/opaque-render-system.cpp
> +            metalness_map = material.ambient_occlusion_textures.front();
Исправлено

2022-10-12 05:38 UTC, malatindez commented on engine/subsystems/render/detail/opaque-render-system.cpp
> +                if (++opaque_per_frame.num_point_lights >= 32) { break; }
Исправлено

2022-10-12 05:38 UTC, malatindez commented on runtime_directory/assets/shaders/emissive/emissive-ps.hlsl
> +	float3 fragment_position : FRAGMENT_POSITION;
Исправлено

2022-10-12 05:39 UTC, malatindez commented on runtime_directory/assets/shaders/emissive/emissive-vs.hlsl
> +	output.normal = mul(input.normal, (float3x3)world_transform);
Исправлено

2022-10-12 05:41 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +#ifndef MAX_POINT_LIGHTS
В данном случае лучше уж оверрайдить их при помощи макро, ибо шейдер находится в папке assets, которая по сути может быть где угодно относительно исходного кода

2022-10-12 05:43 UTC, malatindez commented on runtime_directory/assets/shaders/post-processing/hdr-to-ldr-ps.hlsl
> +  const float gamma = 1.0f / 2.2f;
Исправил: убрал гамма-коррекцию.
Текстуры кубиков пока не трогал

2022-10-12 05:44 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/ps-helpers.hlsli
> +  if (RoS < 0.0)
Исправил

2022-10-12 05:44 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/ps-helpers.hlsli
> +    float attenuation = (1.0f - cosa); // solid_angle / 2.0f * float(std::numbers::pi)
Исправил

2022-10-12 05:44 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/ps-helpers.hlsli
> +    return F * G * saturate(D * attenuation / (4 * ndotv));
Разве не наоборот, `min(..., 1)`?

2022-10-12 05:45 UTC, malatindez commented on runtime_directory/assets/shaders/emissive/emissive-ps.hlsl
> +	bool use_emissive_texture : USE_EMISSIVE_TEXTURE;
Исправлено, перенёс в instance данные

2022-10-12 05:45 UTC, malatindez commented on runtime_directory/assets/shaders/emissive/emissive-vs.hlsl
> +	int use_emissive_texture;
Исправлено для всех шейдеров

2022-10-12 07:45 UTC, malatindez commented on runtime_directory/assets/shaders/post-processing/hdr-to-ldr-ps.hlsl
> +  ldr = AdjustGamma(ldr, gamma);
Исправлено

2022-10-12 07:50 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/ps-helpers.hlsli
> +    return F * G * saturate(D * attenuation / (4 * ndotv));
Исправлено

2022-10-12 07:58 UTC, malatindez commented on runtime_directory/assets/shaders/emissive/emissive-vs.hlsl
> +	output.power = power;
Исправлено

2022-10-12 07:58 UTC, malatindez commented on engine/subsystems/render/detail/emissive-render-system.cpp
> +                        buffer.emissive_color = material.emissive_color;
Исправлено

2022-10-12 07:58 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/ps-helpers.hlsli
> +  float3 color;
Исправлено

2022-10-12 07:58 UTC, malatindez commented on d3d_test/controller.cpp
> +        render::ModelSystem::instance().AddEmissiveInstance(model_id, registry, entity, { render::EmissiveMaterial(vec3{0.988, 0.933, 0.655}, 5) });
Исправлено

2022-10-12 11:54 UTC, malatindez commented on runtime_directory/assets/shaders/post-processing/hdr-to-ldr-ps.hlsl
> +  const float gamma = 1.0f / 2.2f;
Исправлено

2022-10-13 15:58 UTC, malatindez commented on engine/core/math/mat_math.inl
> +        for (size_t i = 0; i < U::size.x; i++)
Вынес в репозиторий `malatindez/math`

2022-10-17 09:04 UTC, e-kabirov commented on runtime_directory/assets/shaders/emissive/emissive-ps.hlsl
> +	// WORKAROUND FOR SPHERES
Зачем Workaround, измени генерацию меша в C++

2022-10-17 09:13 UTC, e-kabirov commented on runtime_directory/assets/shaders/opaque/ps-helpers.hlsli
> +float clampVal = 0.001f;
У тебя это униформа шейдера, а не константа, ты должен static const добавлять, либо же просто const, но внутри функции делать

2022-10-17 09:16 UTC, e-kabirov commented on runtime_directory/assets/shaders/emissive/emissive-ps.hlsl
> +	bool use_emissive_texture : USE_EMISSIVE_TEXTURE;
Нет, это нужно было вынести как униформу наоборот, зачем это в инстанс данных? Это значение не меняется для всех инстансов в Draw Call, у тебя это по C++ коду видно

2022-10-17 09:31 UTC, e-kabirov commented
Некорректный размер спекулярного блика

![image](https://user-images.githubusercontent.com/111517008/196142752-93677036-87f9-472a-bbc6-816de300a5d7.png)

2022-10-17 09:51 UTC, e-kabirov commented
Некорректные отражения на кубиках по Y, чекни OpenGL/D3D стиль текстур

![image](https://user-images.githubusercontent.com/111517008/196147279-e7801819-18b7-4dba-a358-ea54f667fb24.png)

![image](https://user-images.githubusercontent.com/111517008/196147410-33fcfa43-9e5b-414a-8cbe-f6fc6034c7c6.png)

2022-10-17 09:52 UTC, e-kabirov commented
Почему правый самый кубик с кривым отражением опять?
![image](https://user-images.githubusercontent.com/111517008/196147639-9faff269-8b4d-464e-8ebd-10cf1798a36b.png)

2022-10-17 09:54 UTC, e-kabirov commented
Если кубик или сферу захватить мышкой и летать с ней, она периодически дёргается

2022-10-17 10:04 UTC, e-kabirov commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +Texture2D<float> g_shininess : register(t3);
удали

2022-10-17 10:04 UTC, e-kabirov commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +Texture2D<float3> g_ambient : register(t0);
удали

2022-10-17 10:05 UTC, e-kabirov commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +    float g_shininess_value;
удали

2022-10-17 10:05 UTC, e-kabirov commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +    float3 g_ambient_color;
удали

2022-10-17 10:05 UTC, e-kabirov commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +    float g_reflectance_value;
удали

2022-10-17 10:05 UTC, e-kabirov commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +    float3 g_reflective_color;
удали

2022-10-17 10:10 UTC, e-kabirov commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +        if(g_enabled_texture_flags & TEXTURE_NORMAL_SRGB)
Зачем это вообще? Все текстуры нормалей считаются линейными, удали всю логику эту

2022-10-17 10:19 UTC, e-kabirov commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +	float2 reflectanceLUT = g_brdf_lut.Sample(g_normal_sampler, float2(material.roughness, max(dot(common_data.normal, common_data.view_dir_normalized), clampVal))).rg;
Почему это называется normal_scampler и почему reflectanceLUT ты с Wrap семплируешь?

2022-10-17 10:44 UTC, e-kabirov commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +    float3 diffuse = material.albedo * (1.0 - material.metalness) * g_irradiance_map.SampleLevel(g_normal_sampler, common_data.normal, 0.0);
g_linear_clamp_sampler используй

2022-10-17 10:44 UTC, malatindez commented on runtime_directory/assets/shaders/emissive/emissive-ps.hlsl
> +	// WORKAROUND FOR SPHERES
Исправлено

2022-10-17 10:44 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/ps-helpers.hlsli
> +float clampVal = 0.001f;
Исправлено

2022-10-17 10:50 UTC, e-kabirov commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +	float2 reflectanceLUT = g_brdf_lut.Sample(g_normal_sampler, float2(material.roughness, max(dot(common_data.normal, common_data.view_dir_normalized), clampVal))).rg;
SampleLevel(..., 0)

2022-10-17 10:58 UTC, e-kabirov commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +	float2 reflectanceLUT = g_brdf_lut.Sample(g_normal_sampler, float2(material.roughness, max(dot(common_data.normal, common_data.view_dir_normalized), clampVal))).rg;
float2(roughness, 1 - NdotV) там должно быть ещё

2022-10-17 10:59 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +Texture2D<float> g_shininess : register(t3);
Исправлено

2022-10-17 11:00 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +    float3 g_ambient_color;
Исправлено

2022-10-17 11:00 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +    float g_reflectance_value;
Исправлено

2022-10-17 11:00 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +    float3 g_reflective_color;
Исправлено

2022-10-17 11:00 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +        if(g_enabled_texture_flags & TEXTURE_NORMAL_SRGB)
Исправлено

2022-10-17 11:00 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +	float3 specular = reflectance * g_prefiltered_map.SampleLevel(g_linear_clamp_sampler, R, material.roughness * g_prefiltered_map_mip_levels);
Исправлено

2022-10-17 11:08 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +    float g_shininess_value;
Исправлено

2022-10-17 11:08 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +Texture2D<float> g_reflectance : register(t7);
Исправлено

2022-10-17 11:08 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +    float3 diffuse = material.albedo * (1.0 - material.metalness) * g_irradiance_map.SampleLevel(g_normal_sampler, common_data.normal, 0.0);
Исправлено

2022-10-17 11:10 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +	float2 reflectanceLUT = g_brdf_lut.Sample(g_normal_sampler, float2(material.roughness, max(dot(common_data.normal, common_data.view_dir_normalized), clampVal))).rg;
Исправлено

2022-10-19 02:31 UTC, malatindez commented on d3d_test/main.cc
>          render_pipeline->PushLayer(controller);
render-pipeline скорее неправильное название, этот класс отвечает за окно, в которое будет рисоваться картинка. Я это сделал для случая, если необходимо рисовать в несколько окон. Layer
На счёт `Update`: разницы нет, исправлю.

2022-10-19 02:33 UTC, malatindez commented on engine/platform/windows/windows-hdr-render-pipeline.cpp
> +        LayerStack::OnRender();
Смысл LayerStack'a в том, что с его помощью можно рисовать в разных классах разную логику, тот же гизмо, или же оверлеи

2022-10-20 19:26 UTC, malatindez commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +    material.albedo = pow(material.albedo, 2.2f);
Исправлено

2022-10-20 19:26 UTC, malatindez commented on runtime_directory/assets/shaders/post-processing/hdr-to-ldr-ps.hlsl
> + // ldr = ApplyGammaCorrection(ldr, g_gamma);
Исправлено

2022-10-23 08:51 UTC, Bonefest reviewed
![image](https://user-images.githubusercontent.com/13932290/197383101-56a8a7ff-57b3-4a2a-a2f8-95413bae0340.png)
У тебя есть баг с отображением от идеально гладких поверхностей

2022-10-23 08:51 UTC, Bonefest commented on engine/subsystems/render/detail/opaque-render-system.cpp
> +                opaque_point_light.radius = length(registry_transform.scale) / sqrt(3.0f);
Напиши, пожалуйста (в виде комментария), почему ты это так считаешь

2022-10-23 08:51 UTC, Bonefest commented on runtime_directory/assets/shaders/emissive/emissive-ps.hlsl
> +	float3 normal = normalize(input.normal);
Что это за код?

2022-10-23 08:51 UTC, Bonefest commented on runtime_directory/assets/shaders/emissive/emissive-vs.hlsl
> +	bool use_emissive_texture : USE_EMISSIVE_TEXTURE;
В идеале, мы не должны интерполировать атрибуты, которые имеют одно и то же значение на всю модель. Попробуй применить квалификатор `nointerpolation`. Есть и другой подход, чтобы избежать загромождения вершин: использовать константный буфер и в пиксельном шейдере использовать `SV_InstanceID`, но это подойдет только для небольших атрибутов. В случае с матрицами, первый подход все равно лучше.

Я знаю, что раньше uint можно было указывать как линейный квалификатор, но мне кажется, что это поменялось (не помню только в hlsl ли). Если с `nointerpolation` всё будет работать также - все равно оставь его. Как по мне, так код будет более явным.

Для `power`, кстати, `nointerpolation` нужен тоже, но тут уже почти без сомнений (разве что компилятор сообразит и соптимайзит)

2022-10-23 08:51 UTC, Bonefest commented on runtime_directory/assets/shaders/opaque/opaque-ps.hlsl
> +#ifndef MAX_POINT_LIGHTS
Понял, обычно в движках папка с шейдерами лежит всегда в одном и том же месте и все новые проекты знают точное относительно расположение к ней. Я не буду форсить чтобы ты это делал, но само по себе иметь несколько копий констант не очень удобно, особенно когда их количество начинает расти.

2022-10-23 15:06 UTC, malatindez commented on engine/subsystems/render/detail/opaque-render-system.cpp
> +                opaque_point_light.radius = length(registry_transform.scale) / sqrt(3.0f);
Потому что `length` вектора `(1,1,1)` равен `sqrt(1 + 1 + 1)` или же `sqrt(3)`, поэтому чтобы найти радиус, необходимо разделить на `sqrt(3.0f)`. Сама модель сферы у нас изначально имеет радиус `1`.

2022-10-23 15:07 UTC, malatindez commented on runtime_directory/assets/shaders/emissive/emissive-ps.hlsl
> +	float3 normal = normalize(input.normal);
Поставил `return` для теста, а потом забыл убрать. Исправлю.

2022-10-23 15:07 UTC, malatindez commented on runtime_directory/assets/shaders/emissive/emissive-vs.hlsl
> +	bool use_emissive_texture : USE_EMISSIVE_TEXTURE;
Исправлено

2022-10-23 17:38 UTC, Bonefest commented on engine/subsystems/render/detail/opaque-render-system.cpp
> +                opaque_point_light.radius = length(registry_transform.scale) / sqrt(3.0f);
Понял, я про с++ комментарий говорил) Вообще немного странная логика, почему просто не взять любой из компонентов (если у нас изоморфная трансформация)? Если у нас трансформация анизоморфная, значит это уже не сфера, а эллипсоид, наверное какой-то будет. Или, например, взять max3(scale) - тогда мы берём радиус как бы ААББ полученной "сферы".

2022-10-24 10:33 UTC, malatindez commented on engine/direct3d11/states.cpp
> +        sampler_desc = CreateSamplerState(D3D11_FILTER_MIN_MAG_LINEAR_MIP_POINT, D3D11_TEXTURE_ADDRESS_CLAMP);
Исправлено

2022-10-26 16:11 UTC, malatindez commented on engine/platform/windows/windows-hdr-render-pipeline.cpp
> +        window_ = std::make_shared<Window>();
Исправлено

2022-10-26 16:12 UTC, malatindez commented on engine/platform/windows/windows-hdr-render-pipeline.cpp
> +namespace engine::platform::windows
Исправлено

2022-10-26 16:12 UTC, malatindez commented on d3d_test/main.cc
>          render_pipeline->PushLayer(controller);
Исправлено

2022-10-26 16:12 UTC, malatindez commented on d3d_test/main.cc
>          app.PushLayer(input_layer);
Не совсем понял замечание

2023-01-18 10:43 UTC, merged